# Generated by Django 3.2.3 on 2021-06-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_operation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='data',
        ),
        migrations.AddField(
            model_name='operation',
            name='annee_d_individualisation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='annee_de_livraison',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='cao_attribution',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='codeuai',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='entreprise',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='enveloppe_prev_en_meu',
            field=models.DecimalField(decimal_places=90, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='operation',
            name='etat_d_avancement',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='latitude',
            field=models.DecimalField(decimal_places=90, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='operation',
            name='longitude',
            field=models.DecimalField(decimal_places=90, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='operation',
            name='lycee',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='maitrise_d_oeuvre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='mode_de_devolution',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='montant_des_ap_votes_en_meu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operation',
            name='notification_du_marche',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='ppi',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='titreoperation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='ville',
            field=models.CharField(default='', max_length=255),
        ),
    ]
