# Generated by Django 3.2.3 on 2021-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20210601_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='annee_d_individualisation',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='annee_de_livraison',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='cao_attribution',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='codeuai',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='enveloppe_prev_en_meu',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='etat_d_avancement',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='lycee',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='maitrise_d_oeuvre',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='mode_de_devolution',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='montant_des_ap_votes_en_meu',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='notification_du_marche',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='ppi',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='titreoperation',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='ville',
        ),
        migrations.AddField(
            model_name='operation',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
